name: Default libsarus workflow
on: [ push ]

permissions:
  contents: write
  packages: read

jobs:
  check-format:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/sarus-suite/libsarus/formatting:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Check formatting
        uses: ./.github/actions/check-format

  check-runner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Check runner compatibility
        uses: ./.github/actions/check-runner

  build_and_test-opensuseleap_15:
    runs-on: ubuntu-latest
    needs: [ check-format, check-runner ]
    container:
      image: ghcr.io/sarus-suite/libsarus/opensuseleap:15
      options: --user root --privileged
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Initialize git repository
        shell: bash
        run: git config --global --add safe.directory '*'
      - name: Build
        uses: ./.github/actions/build
      - name: Test
        uses: ./.github/actions/test

  build_and_test-rockylinux_9:
    runs-on: ubuntu-latest
    needs: [ check-format, check-runner ]
    container:
      image: ghcr.io/sarus-suite/libsarus/rockylinux:9
      options: --user root --privileged
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Initialize git repository
        shell: bash
        run: git config --global --add safe.directory '*'
      - name: Build
        uses: ./.github/actions/build
      - name: Test
        uses: ./.github/actions/test

  build_and_test-ubuntu_22_04:
    runs-on: ubuntu-latest
    needs: [ check-format, check-runner ]
    container:
      image: ghcr.io/sarus-suite/libsarus/ubuntu:22.04
      options: --user root --privileged
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Initialize git repository
        shell: bash
        run: git config --global --add safe.directory '*'
      - name: Build
        uses: ./.github/actions/build
      - name: Test
        uses: ./.github/actions/test

  release-opensuseleap_15:
    runs-on: ubuntu-latest
    needs: [ build_and_test-opensuseleap_15 ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Release build on OpenSUSE Leap 15
        uses: ./.github/actions/release
        with:
          tag: opensuseleap_15
          github_token: ${{ secrets.GITHUB_TOKEN }}

  release-rockylinux_9:
    runs-on: ubuntu-latest
    needs: [ build_and_test-rockylinux_9 ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Release build on OpenSUSE Leap 15
        uses: ./.github/actions/release
        with:
          tag: rockylinux_9
          github_token: ${{ secrets.GITHUB_TOKEN }}

  release-ubuntu_22_04:
    runs-on: ubuntu-latest
    needs: [ build_and_test-ubuntu_22_04 ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Release build on OpenSUSE Leap 15
        uses: ./.github/actions/release
        with:
          tag: ubuntu_22_04
          github_token: ${{ secrets.GITHUB_TOKEN }}
