name: Default libsarus workflow
on: [ push ]

permissions:
  packages: read

jobs:
  check-format:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/sarus-suite/libsarus/formatting:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Check formatting
        uses: ./.github/actions/check-format

  check-runner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Check runner compatibility
        uses: ./.github/actions/check-runner

  build-opensuseleap_15:
    runs-on: ubuntu-latest
    needs: [ check-format, check-runner ]
    container:
      image: ghcr.io/sarus-suite/libsarus/opensuseleap:15
      options: --user root
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Build on OpenSUSE Leap 15
        uses: ./.github/actions/build
        with:
          tag: opensuseleap_15

  build-rockylinux_9:
    runs-on: ubuntu-latest
    needs: [ check-format, check-runner ]
    container:
      image: ghcr.io/sarus-suite/libsarus/rockylinux:9
      options: --user root
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Build on Rockylinux 9
        uses: ./.github/actions/build
        with:
          tag: rockylinux_9

  build-ubuntu_22_04:
    runs-on: ubuntu-latest
    needs: [ check-format, check-runner ]
    container:
      image: ghcr.io/sarus-suite/libsarus/rockylinux:9
      options: --user root
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Build on Ubuntu 22.04
        uses: ./.github/actions/build
        with:
          tag: ubuntu_22_04

  test-opensuseleap_15:
    runs-on: ubuntu-latest
    needs: [ build-opensuseleap_15 ]
    container:
      image: ghcr.io/sarus-suite/libsarus/opensuseleap:15
      options: --user root
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Test on OpenSUSE Leap 15
        uses: ./.github/actions/test
        with:
          tag: opensuseleap_15

  test-rockylinux_9:
    runs-on: ubuntu-latest
    needs: [ build-rockylinux_9 ]
    container:
      image: ghcr.io/sarus-suite/libsarus/opensuseleap:15
      options: --user root
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Test on Rockylinux 9
        uses: ./.github/actions/test
        with:
          tag: rockylinux_9

  test-ubuntu_22_04:
    runs-on: ubuntu-latest
    needs: [ build-ubuntu_22_04 ]
    container:
      image: ghcr.io/sarus-suite/libsarus/opensuseleap:15
      options: --user root
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Test on Ubuntu 22.04
        uses: ./.github/actions/test
        with:
          tag: ubuntu_22_04

  release-opensuseleap_15:
    runs-on: ubuntu-latest
    needs: [ build-opensuseleap_15 ]  # FIXME: should be 'test-*'
    container:
      image: ghcr.io/sarus-suite/libsarus/opensuseleap:15
      options: --user root
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Test on OpenSUSE Leap 15
        uses: ./.github/actions/test
        with:
          tag: opensuseleap_15
