name: Default libsarus workflow
on: [ push ]

permissions:
  packages: read

jobs:
  check-format:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/sarus-suite/libsarus/formatting:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check formatting
        uses: ./.github/actions/check-format

  check-runner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check runner compatibility
        uses: ./.github/actions/check-runner
