name: Default libsarus workflow
on: [push]

jobs:
  check-format:
    runs-on: ubuntu-latest
    container:
      image: jfrog.svc.cscs.ch/vcef/libsarus/formatting:latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/check-format

  check-runner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/check-runner
