name: Default libsarus workflow
on: [ push ]

permissions:
  contents: write
  packages: read

jobs:
  check-format:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/sarus-suite/libsarus/formatting:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Check formatting
        uses: ./.github/actions/check-format

  check-runner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Check runner compatibility
        uses: ./.github/actions/check-runner

  build_and_test-opensuseleap_15_6:
    runs-on: ubuntu-latest
    needs: [ check-format, check-runner ]
    container:
      image: ghcr.io/sarus-suite/libsarus/opensuseleap_15_6:no-spack
      options: --user root --privileged
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Build and test
        uses: ./.github/actions/build_and_test
        with:
          cache-tag: opensuseleap_15_6

  build_and_test-rockylinux_9:
    runs-on: ubuntu-latest
    needs: [ check-format, check-runner ]
    container:
      image: ghcr.io/sarus-suite/libsarus/rockylinux_9:no-spack
      options: --user root --privileged
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Build and test
        uses: ./.github/actions/build_and_test
        with:
          artifact-tag: rockylinux_9

  build_and_test-ubuntu_22_04:
    runs-on: ubuntu-latest
    needs: [ check-format, check-runner ]
    container:
      image: ghcr.io/sarus-suite/libsarus/ubuntu_22_04:no-spack
      options: --user root --privileged
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Build and test
        uses: ./.github/actions/build_and_test
        with:
          cache-tag: ubuntu_22_04
