name: Default libsarus workflow
on: [ push ]

permissions:
  packages: read

jobs:
  check-format:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/sarus-suite/libsarus/formatting:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Check formatting
        uses: ./.github/actions/check-format

  check-runner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Check runner compatibility
        uses: ./.github/actions/check-runner

  build-opensuseleap_15:
    runs-on: ubuntu-latest
    needs: [ check-format, check-runner ]
    container:
      image: ghcr.io/sarus-suite/libsarus/opensuseleap:15
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: WORKAROUND for EACCES from node_fs_2368
        run: rm -rf ${GITHUB_WORKSPACE}/*

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Build OpenSUSE Leap 15
        uses: ./.github/actions/build
        with:
          image-name: opensuseleap:15

  build-rockylinux_9:
    runs-on: ubuntu-latest
    needs: [ check-format, check-runner ]
    container:
      image: ghcr.io/sarus-suite/libsarus/rockylinux:9
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Build Rockylinux 9
        uses: ./.github/actions/build
        with:
          image-name: rockylinux:9

  build-ubuntu_22_04:
    runs-on: ubuntu-latest
    needs: [ check-format, check-runner ]
    container:
      image: ghcr.io/sarus-suite/libsarus/rockylinux:9
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Build Ubuntu 22.04
        uses: ./.github/actions/build
        with:
          image-name: ubuntu:22.04
